export const FETCH_DEPARTMENTS = "FETCH_DEPARTMENTS";
export const STORE_USER_INFO = "STORE_USER_INFO";
export const TOGGLE_VIEW = "TOGGLE_VIEW";

export const SET_VIEW_MODE = "SET_VIEW_MODE";
export const SET_LOCALE = "SET_LOCALE";

export const FETCH_ADDRESS = "FETCH_ADDRESS";
export const SAVE_ADDRESS = "SAVE_ADDRESS";

export const TOGGLE_TOAST = "TOGGLE_TOAST";

export const FETCH_NO_OF_CARTS = "FETCH_NO_OF_CARTS";

export const INCREMENT_CART = "INCREMENT_CART";

export const UPDATE_ADDRESS = "UPDATE_ADDRESS";

export const DELETE_ADDRESS = "DELETE_ADDRESS";

export const TOGGLE_POPUP = "TOGGLE_POPUP";
export const FETCH_DETAILS_POPUP = "FETCH_DETAILS_POPUP";

export const NEW_NOTIFICATION = " NEW_NOTIFICATION";

export const FETCH_NOTIFICATION = " FETCH_NOTIFICATION";

export const MARK_NOTIFICATION_SEEN = " MARK_NOTIFICATION_SEEN";

export const ADD_TO_CART_POPUP = "ADD_TO_CART_POPUP";

export const START_FETCH_NOTIFICATIONS = "START_FETCH_NOTIFICATIONS";

export const FETCH_MORE_NOTIFICATION = "FETCH_MORE_NOTIFICATION";

export const START_FETCH_MORE_NOTIFICATION = "START_FETCH_MORE_NOTIFICATION";
